'use client';

import { useEffect, useRef, useState } from 'react';
import { Check, Copy, X } from 'lucide-react';

import { generateGeorgianFbPost } from '@/lib/fbPostBuilder';
import { cn } from '@/lib/utils';

import type { CleanListing } from '@/types/database';

export type FbPostModalProps = {
  /** Lead whose generated Georgian post is previewed and copied. */
  listing: CleanListing;
  /** Renders nothing while closed. */
  isOpen: boolean;
  /** Closes the overlay (scrim click / ✕ / Esc). */
  onClose: () => void;
};

type CopyState = 'idle' | 'ok' | 'fail';

const COPY_FEEDBACK_MS = 1600;

/**
 * One-click Facebook hand-off: previews the emoji-structured Georgian post
 * generated by `lib/fbPostBuilder.ts` and copies it to the clipboard. Text
 * is pre-selected in a `whitespace-pre-wrap` plate so line breaks survive
 * exactly as generated. Overlay chrome mirrors `PhoneQrModal` — same scrim,
 * brutalist plate, Esc-to-close with the listener declared before the early
 * return so hook order stays unconditional.
 */
export function FbPostModal({ listing, isOpen, onClose }: FbPostModalProps) {
  const [copyState, setCopyState] = useState<CopyState>('idle');
  const copyTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  /* Clear the copy-feedback timer on unmount. */
  useEffect(
    () => () => {
      if (copyTimerRef.current !== null) clearTimeout(copyTimerRef.current);
    },
    [],
  );

  /* Esc closes the overlay. */
  useEffect(() => {
    if (!isOpen) return;
    const handleKeyDown = (event: KeyboardEvent): void => {
      if (event.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const post = generateGeorgianFbPost(listing);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(post);
      setCopyState('ok');
    } catch {
      setCopyState('fail');
    }
    if (copyTimerRef.current !== null) clearTimeout(copyTimerRef.current);
    copyTimerRef.current = setTimeout(() => setCopyState('idle'), COPY_FEEDBACK_MS);
  };

  return (
    <div
      className="fixed inset-0 z-[60] grid place-items-center bg-slate-900/20 p-4 backdrop-blur-sm"
      onClick={onClose}
    >
      <div
        role="dialog"
        aria-modal="true"
        aria-label="Georgian Facebook post"
        onClick={(event) => event.stopPropagation()}
        className="w-full max-w-md rounded-2xl border border-slate-200 bg-white shadow-xl"
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-200 px-4 py-3">
          <h2 className="flex items-center gap-2 font-mono text-[11px] font-bold uppercase tracking-[0.18em] text-ink">
            <span className="rounded-md bg-accent px-1.5 py-0.5 text-[10px] font-black text-white">SOTP</span>
            {' // FB პოსტი'}
          </h2>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close post preview"
            title="Close post preview"
            className="flex size-6 items-center justify-center rounded-md text-muted transition-colors hover:text-alert"
          >
            <X className="size-3.5" aria-hidden />
          </button>
        </div>

        {/* Preview plate — pre-wrap keeps the generated breaks intact */}
        <pre className="max-h-[45vh] select-all overflow-y-auto whitespace-pre-wrap break-words px-4 py-3 font-mono text-[11px] leading-5 text-ink">
          {post}
        </pre>

        {/* Copy action */}
        <div className="border-t border-slate-200 px-4 py-3">
          <button
            type="button"
            onClick={() => void handleCopy()}
            title={copyState === 'fail' ? 'Copy failed — click to retry' : 'Copy post text'}
            className={cn(
              'flex w-full items-center justify-center gap-1.5 rounded-lg border py-2 font-mono text-[10px] font-bold uppercase tracking-[0.1em] transition-colors',
              copyState === 'ok'
                ? 'border-accent bg-accent text-white'
                : copyState === 'fail'
                  ? 'border-alert text-alert hover:bg-paper'
                  : 'border-slate-200 text-muted hover:bg-paper hover:text-ink',
            )}
          >
            {copyState === 'ok' ? (
              <>
                <Check className="size-3.5" aria-hidden />
                <span role="status">დაკოპირდა!</span>
              </>
            ) : (
              <>
                <Copy className="size-3.5" aria-hidden />
                <span role="status">{copyState === 'fail' ? 'ხელახლა' : 'ტექსტის კოპირება'}</span>
              </>
            )}
          </button>
          <p className="mt-2 font-mono text-[9px] uppercase tracking-[0.12em] text-muted">
            paste into facebook · esc to close
          </p>
        </div>
      </div>
    </div>
  );
}
